In [78]:
import tensorflow as tf

x1_data = tf.constant([73., 93., 89., 96., 73.])
x2_data = tf.constant([80., 88., 91., 98., 66.])
x3_data = tf.constant([75., 93., 90., 100., 70.])
y_data = tf.constant([152., 185., 180., 196., 142.])

x1 = tf.Variable(1., shape=tf.TensorShape(None), dtype=tf.float32)
x2 = tf.Variable(1., shape=tf.TensorShape(None), dtype=tf.float32)
x3 = tf.Variable(1., shape=tf.TensorShape(None), dtype=tf.float32)
y = tf.Variable(1., shape=tf.TensorShape(None), dtype=tf.float32)

w1 = tf.Variable(tf.random.normal([1]), dtype=tf.float32, name='weight1')
w2 = tf.Variable(tf.random.normal([1]), dtype=tf.float32, name='weight2')
w3 = tf.Variable(tf.random.normal([1]), dtype=tf.float32, name='weight3')
b = tf.Variable(tf.random.normal([1]), dtype=tf.float32, name='bias')

def hypothesis():
    return x1 * w1 + x2 * w2 + x3 * w3 + b

def cost():
    return tf.reduce_mean(tf.square(hypothesis() - y))

def optimizer():
    return tf.keras.optimizers.SGD(learning_rate = 1e-5)

def train():
    return optimizer().minimize(cost, var_list=[w1, w2, w3])

for step in range(2001):
    x1.assign(x1_data)
    x2.assign(x2_data)
    x3.assign(x3_data)
    y.assign(y_data)
    train()
    if (step % 10 == 0):
        print(step, "Cost: ", cost().numpy(), "\nPrediction:\n", hypothesis().numpy())

0 Cost:  18838.74 
Prediction:
 [27.154041 39.719173 35.177235 41.424145 29.601856]
10 Cost:  3.7012737 
Prediction:
 [148.56264 185.63808 178.95694 197.99599 140.89917]
20 Cost:  3.5239913 
Prediction:
 [148.93355 186.07745 179.39328 198.46994 141.2337 ]
30 Cost:  3.5192628 
Prediction:
 [148.9381  186.0765  179.39575 198.4714  141.23239]
40 Cost:  3.5145936 
Prediction:
 [148.94153 186.07425 179.39693 198.47148 141.23007]
50 Cost:  3.5099208 
Prediction:
 [148.94495 186.07199 179.39809 198.47153 141.22777]
60 Cost:  3.505281 
Prediction:
 [148.94835 186.06973 179.39923 198.47157 141.22546]
70 Cost:  3.5006614 
Prediction:
 [148.95174 186.06747 179.40036 198.4716  141.22314]
80 Cost:  3.4960454 
Prediction:
 [148.95514 186.06523 179.40149 198.47165 141.22086]
90 Cost:  3.4914443 
Prediction:
 [148.95853 186.06299 179.40265 198.4717  141.21858]
100 Cost:  3.486885 
Prediction:
 [148.9619  186.06076 179.40378 198.47174 141.21631]
110 Cost:  3.4823406 
Prediction:
 [148.96524 186.05852 1

In [77]:
import tensorflow as tf

x_data = tf.constant([
    [73., 80., 75.], [93., 88., 93.], [89., 91., 90.],
    [96., 98., 100.], [73., 66., 70.]
])

y_date = tf.constant([[152.], [185.], [180.], [196.], [142.]])
X = tf.Variable([[1., 1., 1.]], shape=tf.TensorShape(None), dtype=tf.float32)
Y = tf.Variable([[1.]], shape=tf.TensorShape(None), dtype=tf.float32)

W = tf.Variable(tf.random.normal([3, 1]), dtype=tf.float32, name='weight')
b = tf.Variable(tf.random.normal([1]), dtype=tf.float32, name='bias')

def hypothesis():
    return tf.linalg.matmul(X, W) + b

def cost():
    return tf.reduce_mean(tf.square(hypothesis() - y))

def optimizer():
    return tf.keras.optimizers.SGD(learning_rate = 1e-5)

def train():
    return optimizer().minimize(cost, var_list=[W])

for step in range(2001):
    X.assign(x_data)
    Y.assign(y_data)
    train()
    if (step % 10 == 0):
        print(step, "Cost: ", cost().numpy(), "\nPrediction:\n", hypothesis().numpy())

0 Cost:  2894.098 
Prediction:
 [[113.77701]
 [129.82404]
 [131.80875]
 [138.45386]
 [101.70821]]
10 Cost:  787.5157 
Prediction:
 [[154.36423]
 [178.63129]
 [179.8875 ]
 [190.80397]
 [138.9468 ]]
20 Cost:  787.285 
Prediction:
 [[154.47482]
 [178.78818]
 [180.0303 ]
 [190.95288]
 [139.07785]]
30 Cost:  787.0734 
Prediction:
 [[154.46298]
 [178.79776]
 [180.028  ]
 [190.94379]
 [139.09656]]
40 Cost:  786.86304 
Prediction:
 [[154.45074]
 [178.80688]
 [180.02527]
 [190.9342 ]
 [139.11487]]
50 Cost:  786.65234 
Prediction:
 [[154.4386 ]
 [178.81598]
 [180.02255]
 [190.92462]
 [139.13316]]
60 Cost:  786.4432 
Prediction:
 [[154.42648]
 [178.82507]
 [180.01987]
 [190.9151 ]
 [139.1514 ]]
70 Cost:  786.23376 
Prediction:
 [[154.41443]
 [178.83414]
 [180.01718]
 [190.90555]
 [139.16962]]
80 Cost:  786.02545 
Prediction:
 [[154.40237]
 [178.84311]
 [180.01453]
 [190.89604]
 [139.18777]]
90 Cost:  785.8172 
Prediction:
 [[154.3904 ]
 [178.85211]
 [180.01187]
 [190.8865 ]
 [139.2059 ]]
100 Cost