In [144]:
import numpy as np

xy = np.loadtxt('resource/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, :-1]
y_data = xy[:, [-1]]

print(xy)
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]]
(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [8]:
import tensorflow as tf
import numpy as np
tf.keras.utils.set_random_seed(777)

xy = np.loadtxt('resource/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, :-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

X = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))
Y = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))

W = tf.Variable(tf.random.normal([3, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

def hypothesis():
    return tf.linalg.matmul(X, W) + b

def cost():
    return tf.reduce_mean(tf.square(hypothesis() - Y))

def optimizer():
    return tf.keras.optimizers.SGD(learning_rate = 1e-5)

def train():
    return optimizer().minimize(cost, var_list=[W, b])


X.assign(x_data)
Y.assign(y_data)
for step in range(2001):
    train()
    if step % 10 == 0:
        print(step, "Cost: ", cost().numpy(), "\nPrediction:\n", hypothesis().numpy())

# Ask my score
X.assign([[100, 70, 101]])
print("your score will be: ", hypothesis().numpy())

# Ask other scores
X.assign([[60, 70, 110], [90, 100, 80]])
print("other scores will be: ", hypothesis().numpy())

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]
0 Cost:  2138.3694 
Prediction:
 [[108.75247]
 [131.83595]
 [129.53914]
 [139.9543 ]
 [101.47267]
 [ 72.65274]]
10 Cost:  0.6653157 
Prediction:
 [[151.85683]
 [183.66026]
 [180.59402]
 [195.55423]
 [141.00356]
 [101.795  ]]
20 Cost:  0.56703234 
Prediction:
 [[152.14813]
 [184.0116 ]
 [180.93959]
 [195.93044]
 [141.27194]
 [101.99276]]
30 Cost:  0.56680936 
Prediction:
 [[152.14952 ]
 [184.01433 ]
 [180.94174 ]
 [195.93263 ]
 [141.27441 ]
 [101.994514]]
40 Cost:  0.5665827 
Prediction:
 [[152.1489 ]
 [184.0147 ]
 [180.94154]
 [195.93228]
 [141.27505]
 [101.99492]]
50 Cost:  0.5663514 
Prediction:
 [[152.1483  ]
 [184.01506 ]
 [180.94135 ]
 [195.93195 ]
 [141.27571 ]
 [101.995316]]
60 Cost:  0.5661358 
Prediction:
 [[152.14769]
 [184.01541]
 [180.94116]
 [195.93161]
 [141.27635]
 [101.99572]]
70 Cost:  0.5659046 
P

In [13]:
import tensorflow as tf
import numpy as np

dataset = tf.data.experimental.make_csv_dataset('resource/data-01-test-score.csv', batch_size=10, num_epochs=1, shuffle=False)

X = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))
Y = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))

W = tf.Variable(tf.random.normal([3, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

def hypothesis():
    return tf.linalg.matmul(X, W) + b

def cost():
    return tf.reduce_mean(tf.square(hypothesis() - Y))

def optimizer():
    return tf.keras.optimizers.SGD(learning_rate = 1e-5)

def train():
    return optimizer().minimize(cost, var_list=[W, b])

i = 0
for dict in dataset.as_numpy_iterator():
    temp = np.array(list(dict.values())).swapaxes(0, 1)
    x_data = temp[:, :-1]
    y_data = temp[:, [-1]]
    print(x_data)
    print(y_data)
    X.assign(x_data)
    Y.assign(y_data)
    for step in range(2001):
        train()
        if step % 200 == 0:
            print(i, step, "Cost: ", cost().numpy(), "\nPrediction:\n", hypothesis().numpy())
    i+=1

# Ask my score
X.assign([[100, 70, 101]])
print("your score will be: ", hypothesis().numpy())

# Ask other scores
X.assign([[60, 70, 110], [90, 100, 80]])
print("other scores will be: ", hypothesis().numpy())

[[ 73  80  75]
 [ 93  88  93]
 [ 89  91  90]
 [ 96  98 100]
 [ 73  66  70]
 [ 53  46  55]]
[[152]
 [185]
 [180]
 [196]
 [142]
 [101]]
0 0 Cost:  17431.29 
Prediction:
 [[31.620869]
 [33.21125 ]
 [35.299213]
 [36.99101 ]
 [25.367119]
 [15.962569]]
0 200 Cost:  5.3617463 
Prediction:
 [[155.31546]
 [182.28198]
 [181.97256]
 [196.74971]
 [139.14088]
 [ 99.92159]]
0 400 Cost:  4.8147383 
Prediction:
 [[155.1196 ]
 [182.37976]
 [181.89508]
 [196.69087]
 [139.27727]
 [100.10057]]
0 600 Cost:  4.3351817 
Prediction:
 [[154.93634]
 [182.4713 ]
 [181.82265]
 [196.63547]
 [139.40529]
 [100.26769]]
0 800 Cost:  3.9147003 
Prediction:
 [[154.7649  ]
 [182.55705 ]
 [181.75499 ]
 [196.5833  ]
 [139.52548 ]
 [100.423706]]
0 1000 Cost:  3.5459566 
Prediction:
 [[154.60454]
 [182.63739]
 [181.69177]
 [196.53423]
 [139.63838]
 [100.56934]]
0 1200 Cost:  3.2225037 
Prediction:
 [[154.45451 ]
 [182.71265 ]
 [181.63274 ]
 [196.48798 ]
 [139.74443 ]
 [100.705284]]
0 1400 Cost:  2.9387417 
Prediction:
 [[154