In [144]:
import numpy as np

xy = np.loadtxt('resource/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, :-1]
y_data = xy[:, [-1]]

print(xy)
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]]
(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [175]:
import tensorflow as tf
import numpy as np
tf.keras.utils.set_random_seed(777)

xy = np.loadtxt('resource/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, :-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

X = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))
Y = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))

W = tf.Variable(tf.random.normal([3, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

def hypothesis():
    return tf.linalg.matmul(X, W) + b

def cost():
    return tf.reduce_mean(tf.square(hypothesis() - Y))

def optimizer():
    return tf.keras.optimizers.SGD(learning_rate = 1e-5)

def train():
    return optimizer().minimize(cost, var_list=[W])

for step in range(2001):
    X.assign(x_data)
    Y.assign(y_data)
    train()
    if step % 10 == 0:
        print(step, "Cost: ", cost().numpy(), "\nPrediction:\n", hypothesis().numpy())

# Ask my score
X.assign([[100, 70, 101]])
print("your score will be: ", hypothesis().numpy())

# Ask other scores
X.assign([[60, 70, 110], [90, 100, 80]])
print("other scores will be: ", hypothesis().numpy())

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]
0 Cost:  2138.5046 
Prediction:
 [[108.75098 ]
 [131.83446 ]
 [129.53764 ]
 [139.9528  ]
 [101.471176]
 [ 72.651245]]
10 Cost:  0.66498524 
Prediction:
 [[151.85645]
 [183.66057]
 [180.59425]
 [195.5548 ]
 [141.0029 ]
 [101.79352]]
20 Cost:  0.5666501 
Prediction:
 [[152.14784]
 [184.01201]
 [180.93994]
 [195.93114]
 [141.27136]
 [101.99135]]
30 Cost:  0.56642526 
Prediction:
 [[152.14922]
 [184.01472]
 [180.94208]
 [195.93332]
 [141.27382]
 [101.99309]]
40 Cost:  0.56618994 
Prediction:
 [[152.1486 ]
 [184.0151 ]
 [180.94186]
 [195.933  ]
 [141.27448]
 [101.99351]]
50 Cost:  0.5659626 
Prediction:
 [[152.148   ]
 [184.01546 ]
 [180.94167 ]
 [195.93266 ]
 [141.27513 ]
 [101.993904]]
60 Cost:  0.56574106 
Prediction:
 [[152.1474  ]
 [184.01584 ]
 [180.9415  ]
 [195.93233 ]
 [141.27579 ]
 [101.994316]]
70 Cost:  0.56

In [178]:
import tensorflow as tf
import numpy as np

dataset = tf.data.experimental.make_csv_dataset('resource/data-01-test-score.csv', batch_size=2, num_epochs=1, shuffle=False)

X = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))
Y = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))

W = tf.Variable(tf.random.normal([3, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

def hypothesis():
    return tf.linalg.matmul(X, W) + b

def cost():
    return tf.reduce_mean(tf.square(hypothesis() - Y))

def optimizer():
    return tf.keras.optimizers.SGD(learning_rate = 1e-5)

def train():
    return optimizer().minimize(cost, var_list=[W])

i = 0
for dict in dataset.as_numpy_iterator():
    temp = np.array(list(dict.values())).swapaxes(0, 1)
    x_data = temp[:, :-1]
    y_data = temp[:, [-1]]
    print(x_data)
    print(y_data)
    for step in range(200):
        X.assign(x_data)
        Y.assign(y_data)
        train()
        if step % 10 == 0:
            print(i, step, "Cost: ", cost().numpy(), "\nPrediction:\n", hypothesis().numpy())
    i+=1

# Ask my score
X.assign([[100, 70, 101]])
print("your score will be: ", hypothesis().numpy())

# Ask other scores
X.assign([[60, 70, 110], [90, 100, 80]])
print("other scores will be: ", hypothesis().numpy())

[[73 80 75]
 [93 88 93]]
[[152]
 [185]]
0 0 Cost:  21707.148 
Prediction:
 [[19.716846]
 [24.017193]]
0 10 Cost:  1.1827718 
Prediction:
 [[152.44814]
 [183.5287 ]]
0 20 Cost:  0.8194677 
Prediction:
 [[152.98186]
 [184.17848]]
0 30 Cost:  0.8126237 
Prediction:
 [[152.97993]
 [184.18454]]
0 40 Cost:  0.80585575 
Prediction:
 [[152.97585]
 [184.18794]]
0 50 Cost:  0.7991433 
Prediction:
 [[152.97177]
 [184.19133]]
0 60 Cost:  0.7924712 
Prediction:
 [[152.9677]
 [184.1947]]
0 70 Cost:  0.7858589 
Prediction:
 [[152.96367]
 [184.19809]]
0 80 Cost:  0.7793231 
Prediction:
 [[152.95964]
 [184.20142]]
0 90 Cost:  0.7728171 
Prediction:
 [[152.95563]
 [184.20476]]
0 100 Cost:  0.7663794 
Prediction:
 [[152.95164]
 [184.20808]]
0 110 Cost:  0.7599807 
Prediction:
 [[152.94766]
 [184.2114 ]]
0 120 Cost:  0.7536615 
Prediction:
 [[152.94371]
 [184.21468]]
0 130 Cost:  0.7473688 
Prediction:
 [[152.93976]
 [184.21796]]
0 140 Cost:  0.7411572 
Prediction:
 [[152.93585]
 [184.22122]]
0 150 Cost: 