In [14]:
import numpy as np

xy = np.loadtxt('resource/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, :-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [26]:
import tensorflow as tf
import numpy as np
tf.keras.utils.set_random_seed(777)

xy = np.loadtxt('resource/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, :-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

X = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))
Y = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))

W = tf.Variable(tf.random.normal([3, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

def hypothesis():
    return tf.linalg.matmul(X, W) + b

def cost():
    return tf.reduce_mean(tf.square(hypothesis() - Y))

def optimizer():
    return tf.keras.optimizers.SGD(learning_rate = 1e-5)

def train():
    return optimizer().minimize(cost, var_list=[W])

for step in range(2001):
    X.assign(x_data)
    Y.assign(y_data)
    train()
    if step % 10 == 0:
        print(step, "Cost: ", cost().numpy(), "\nPrediction:\n", hypothesis().numpy())

# Ask my score
X.assign([[100, 70, 101]])
print("your score will be: ", hypothesis().numpy())

# Ask other scores
X.assign([[60, 70, 110], [90, 100, 80]])
print("other scores will be: ", hypothesis().numpy())

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]
0 Cost:  2138.5046 
Prediction:
 [[108.75098 ]
 [131.83446 ]
 [129.53764 ]
 [139.9528  ]
 [101.471176]
 [ 72.651245]]
10 Cost:  0.66498524 
Prediction:
 [[151.85645]
 [183.66057]
 [180.59425]
 [195.5548 ]
 [141.0029 ]
 [101.79352]]
20 Cost:  0.5666501 
Prediction:
 [[152.14784]
 [184.01201]
 [180.93994]
 [195.93114]
 [141.27136]
 [101.99135]]
30 Cost:  0.56642526 
Prediction:
 [[152.14922]
 [184.01472]
 [180.94208]
 [195.93332]
 [141.27382]
 [101.99309]]
40 Cost:  0.56618994 
Prediction:
 [[152.1486 ]
 [184.0151 ]
 [180.94186]
 [195.933  ]
 [141.27448]
 [101.99351]]
50 Cost:  0.5659626 
Prediction:
 [[152.148   ]
 [184.01546 ]
 [180.94167 ]
 [195.93266 ]
 [141.27513 ]
 [101.993904]]
60 Cost:  0.56574106 
Prediction:
 [[152.1474  ]
 [184.01584 ]
 [180.9415  ]
 [195.93233 ]
 [141.27579 ]
 [101.994316]]
70 Cost:  0.56