In [23]:
import tensorflow as tf

In [24]:
mnist = tf.keras.datasets.mnist
nb_classes = 10

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
print(x_train.shape, x_test.shape)
x_train = x_train.reshape(x_train.shape[0], x_train.shape[1] * x_train.shape[2])
x_test = x_test.reshape(x_test.shape[0], x_test.shape[1] * x_test.shape[2])
print(x_train.shape, x_test.shape)

# change result to one-hot
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

# # Consider an array of 5 labels out of a set of 3 classes {0, 1, 2}:
# array([0, 2, 1, 2, 0])
# `to_categorical` converts this into a matrix with as many columns as there are classes. The number of rows
#  stays the same. to_categorical(labels)
# array([[ 1.,  0.,  0.],
#        [ 0.,  0.,  1.],
#        [ 0.,  1.,  0.],
#        [ 0.,  0.,  1.],
#        [ 1.,  0.,  0.]], dtype=float32)

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=10, input_dim=784, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.optimizers.Adam(0.001), metrics=['accuracy'])
tf.model.summary()

(60000, 28, 28) (10000, 28, 28)
(60000, 784) (10000, 784)
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 10)                7850      
                                                                 
Total params: 7850 (30.66 KB)
Trainable params: 7850 (30.66 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [25]:
traning_epochs = 15 # 전체 데이터셋을 한번 돌면 1epochs
batch_size = 100 # 한번에 몇개씩 학습

history = tf.model.fit(x_train, y_train, batch_size=batch_size, epochs=traning_epochs)

Epoch 1/15
600/600 [==============================] - 1s 822us/step - loss: 0.6392 - accuracy: 0.8406
Epoch 2/15
600/600 [==============================] - 0s 823us/step - loss: 0.3474 - accuracy: 0.9060
Epoch 3/15
600/600 [==============================] - 0s 809us/step - loss: 0.3102 - accuracy: 0.9136
Epoch 4/15
600/600 [==============================] - 1s 848us/step - loss: 0.2930 - accuracy: 0.9185
Epoch 5/15
600/600 [==============================] - 1s 886us/step - loss: 0.2826 - accuracy: 0.9211
Epoch 6/15
600/600 [==============================] - 0s 805us/step - loss: 0.2753 - accuracy: 0.9235
Epoch 7/15
600/600 [==============================] - 1s 904us/step - loss: 0.2697 - accuracy: 0.9254
Epoch 8/15
600/600 [==============================] - 0s 831us/step - loss: 0.2658 - accuracy: 0.9260
Epoch 9/15
600/600 [==============================] - 0s 788us/step - loss: 0.2624 - accuracy: 0.9270
Epoch 10/15
600/600 [==============================] - 0s 767us/step - loss: 0.259

In [35]:
predictions = tf.model.predict(x_test)
print('Prediction: \n', predictions)

score = tf.model.evaluate(x_train, y_train)
print('Accuracy: ', score[1])

313/313 [==============================] - 0s 585us/step
Prediction: 
 [[2.44658872e-06 1.06685095e-11 5.51654466e-06 ... 9.95347917e-01
  1.38022224e-05 2.62919086e-04]
 [1.92976149e-04 3.00435340e-06 9.93054926e-01 ... 8.76845198e-18
  2.99366402e-05 4.27843457e-14]
 [1.31496336e-06 9.79096234e-01 1.25107989e-02 ... 7.17356743e-04
  3.00412369e-03 1.90150953e-04]
 ...
 [1.37775382e-08 1.27187807e-08 5.06434480e-06 ... 1.54760422e-03
  6.76120445e-03 1.73230246e-02]
 [1.24087734e-07 4.88148430e-07 2.66411490e-07 ... 8.67445848e-08
  7.33070681e-03 1.15412902e-07]
 [7.81161077e-07 2.15234189e-14 2.92792429e-05 ... 2.17241250e-13
  1.20223822e-08 2.02749102e-11]]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1875/1875 [==============================] - 1s 608us/step - loss: 0.2446 - accuracy: 0.9323
Accuracy:  0.9323166608810425
