In [29]:
import tensorflow as tf

x_data = [[1, 2, 1, 1,], 
          [2, 1, 3, 2], 
          [3, 1, 3, 4], 
          [4, 1, 5, 5], 
          [1, 7, 5, 5], 
          [1, 2, 5, 6], 
          [1, 6, 6, 6], 
          [1, 7, 7, 7]]
y_data = [[0, 0, 1], 
          [0, 0, 1], 
          [0, 0, 1], 
          [0, 1, 0], 
          [0, 1, 0], 
          [0, 1, 0], 
          [1, 0, 0], 
          [1, 0, 0]]
nb_classes = 3

X = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))
Y = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))

W = tf.Variable(tf.random.normal([4, nb_classes], name='weight'))
b = tf.Variable(tf.random.normal([nb_classes], name='bias'))

# softmax activations
# softmax  = exp(logits) / reduce_sum(exp(logits), dim)
def hypothesis(): 
    return tf.nn.softmax(tf.linalg.matmul(X, W) + b)

def cost():
    return tf.reduce_mean(-tf.reduce_sum(Y * tf.math.log(hypothesis()), axis=1))

# 경사하강법
def train():
    return tf.keras.optimizers.SGD(learning_rate = 0.01).minimize(cost, var_list=[W, b])

X.assign(x_data)
Y.assign(y_data)
for step in range(2001):
    train()
    if step % 200 == 0:
        print(step, cost())

# Testing & One-hot encoding
X.assign([[1, 11, 7, 9]])
a = hypothesis()
print(a.numpy(), tf.math.argmax(a, axis=1).numpy())

X.assign([
    [1, 11, 7, 9],
    [1, 3, 4, 3],
    [1, 1, 0, 1]])
all = hypothesis()
print(all.numpy(), tf.math.argmax(all, axis=1).numpy())

0 tf.Tensor(8.627793, shape=(), dtype=float32)
200 tf.Tensor(1.1133552, shape=(), dtype=float32)
400 tf.Tensor(0.8452462, shape=(), dtype=float32)
600 tf.Tensor(0.73607564, shape=(), dtype=float32)
800 tf.Tensor(0.67986023, shape=(), dtype=float32)
1000 tf.Tensor(0.6387895, shape=(), dtype=float32)
1200 tf.Tensor(0.60652155, shape=(), dtype=float32)
1400 tf.Tensor(0.5802393, shape=(), dtype=float32)
1600 tf.Tensor(0.55822766, shape=(), dtype=float32)
1800 tf.Tensor(0.53936327, shape=(), dtype=float32)
2000 tf.Tensor(0.52288043, shape=(), dtype=float32)
[[0.90352404 0.095324   0.00115189]] [0]
[[0.90352404 0.095324   0.00115189]
 [0.27846757 0.6303953  0.09113717]
 [0.0310455  0.11595569 0.85299885]] [0 1 2]


In [32]:
# Lab 6 Softmax Classifier
import tensorflow as tf
import numpy as np

x_raw = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_raw = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.array(x_raw, dtype=np.float32)
y_data = np.array(y_raw, dtype=np.float32)

nb_classes = 3

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(input_dim=4, units=nb_classes, use_bias=True))  # use_bias is True, by default

# use softmax activations: softmax = exp(logits) / reduce_sum(exp(logits), dim)
tf.model.add(tf.keras.layers.Activation('softmax'))

# use loss == categorical_crossentropy
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(learning_rate=0.01), metrics=['accuracy'])
tf.model.summary()
        
history = tf.model.fit(x_data, y_data, epochs=200, steps_per_epoch=10)

print('--------------')
# Testing & One-hot encoding
a = tf.model.predict(np.array([[1, 11, 7, 9]]))
print(a, tf.keras.backend.eval(tf.argmax(a, axis=1)))

print('--------------')
b = tf.model.predict(np.array([[1, 3, 4, 3]]))
print(b, tf.keras.backend.eval(tf.argmax(b, axis=1)))

print('--------------')
# or use argmax embedded method, predict_classes
c = tf.model.predict(np.array([[1, 1, 0, 1]]))
c_onehot = np.argmax(c, axis=-1)
print(c, c_onehot)

print('--------------')
all = tf.model.predict(np.array([[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]))
all_onehot = np.argmax(all, axis=-1)
print(all, all_onehot)

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 3)                 15        
                                                                 
 activation_7 (Activation)   (None, 3)                 0         
                                                                 
Total params: 15 (60.00 Byte)
Trainable params: 15 (60.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/200
10/10 [==============================] - 0s 968us/step - loss: 2.0302 - accuracy: 0.3000
Epoch 2/200
10/10 [==============================] - 0s 841us/step - loss: 2.0255 - accuracy: 0.2000
Epoch 3/200
10/10 [==============================] - 0s 827us/step - loss: 1.0935 - accuracy: 0.6000
Epoch 4/200
10/10 [==============================] - 0s 875us/step - loss: 1.4083 - accuracy: 0.3000
Epoch 5/200


10/10 [==============================] - 0s 897us/step - loss: 0.0000e+00 - accuracy: 0.0000e+00
--------------
1/1 [==============================] - 0s 22ms/step
[[0.70118105 0.29632014 0.00249881]] [0]
--------------
1/1 [==============================] - 0s 12ms/step
[[0.49758804 0.33052796 0.17188393]] [0]
--------------
1/1 [==============================] - 0s 13ms/step
[[0.01180443 0.09475384 0.8934417 ]] [2]
--------------
1/1 [==============================] - 0s 14ms/step
[[0.70118105 0.29632014 0.00249881]
 [0.49758804 0.33052796 0.17188396]
 [0.01180443 0.09475384 0.8934417 ]] [0 0 2]


In [110]:
import tensorflow as tf
import numpy as np

# 동물 데이터
xy = np.loadtxt('resource/data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

# 0 ~ 6 분류
nb_classes = 7 

X = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))
Y = tf.Variable(1, dtype=tf.int32, shape=tf.TensorShape(None))

W = tf.Variable(tf.random.normal([16, nb_classes]), name='weight')
b = tf.Variable(tf.random.normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), sum)
# logits = matmul(X, W) + b
def logits():
    return tf.linalg.matmul(X, W) + b

def hypothesis():
    return tf.nn.softmax(logits())

def Y_one_hot():
    return tf.reshape(tf.one_hot(Y, nb_classes), [-1, nb_classes])

# Corss entropy cost/loss
def cost(): 
    return tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits(),
                                                   labels=Y_one_hot()))
    
# 경사하강법
def train():
    return tf.keras.optimizers.SGD(learning_rate = 0.1).minimize(cost, var_list=[W, b])

def prediction():
    return tf.math.argmax(hypothesis(), axis=1)

def correct_prediction():
    return tf.equal(prediction(), tf.math.argmax(Y_one_hot(), 1))

# 정확도 계산, 예측값과 실 Y값이 얼마나 같은지를 평균
def accuracy():
    return tf.reduce_mean(tf.cast(correct_prediction(), dtype=tf.float32))

X.assign(x_data)
Y.assign(y_data)
for step in range(2000):
    train()
    if step % 200 == 0:
        print("step: ", step, "loss: ", cost().numpy(), "acc: ", accuracy().numpy())

for p, y in zip(prediction(), y_data.flatten()):
    print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

(101, 16) (101, 1)
step:  0 loss:  7.1705565 acc:  0.03960396
step:  200 loss:  0.4605676 acc:  0.84158415
step:  400 loss:  0.24849063 acc:  0.9405941
step:  600 loss:  0.1711615 acc:  0.9405941
step:  800 loss:  0.12919414 acc:  0.980198
step:  1000 loss:  0.1031356 acc:  0.990099
step:  1200 loss:  0.08565845 acc:  0.990099
step:  1400 loss:  0.07326889 acc:  0.990099
step:  1600 loss:  0.06409204 acc:  0.990099
step:  1800 loss:  0.057045456 acc:  1.0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 3 True Y: 3
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
[True] Predic

In [109]:
# Lab 6 Softmax Classifier
import tensorflow as tf
import numpy as np

# Predicting animal type based on various features
xy = np.loadtxt('resource/data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

'''
(101, 16) (101, 1)
'''

nb_classes = 7  # 0 ~ 6

# Convert y_data to one_hot
y_one_hot = tf.keras.utils.to_categorical(y_data, nb_classes)
print("one_hot:", y_one_hot)

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=nb_classes, input_dim=16, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(learning_rate=0.1), metrics=['accuracy'])
tf.model.summary()

history = tf.model.fit(x_data, y_one_hot, epochs=10, steps_per_epoch=200)

# Single data test
test_data = np.array([[0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0]]) # expected prediction == 3 (feathers)
print(tf.model.predict(test_data), np.argmax(tf.model.predict(test_data), axis=-1))

# Full x_data test
pred = np.argmax(tf.model.predict(x_data), axis=-1)
for p, y in zip(pred, y_data.flatten()):
    print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

(101, 16) (101, 1)
one_hot: [[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0

1/1 [==============================] - 0s 12ms/step
[[5.4918360e-03 4.5090462e-03 2.3464952e-02 9.4435561e-01 9.1145635e-03
  2.3888686e-05 1.3040143e-02]] [3]


4/4 [==============================] - 0s 938us/step
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 3 True Y: 3
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 5 True Y: 5
[True] Prediction: 4 True Y: 4
[True] Prediction: 4 True Y: 4
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction