In [5]:
import tensorflow as tf
import numpy as np

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data, y_data)
X = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))
Y = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))

W = tf.Variable(tf.random.normal([4, 1], name='weight'))
b = tf.Variable(tf.random.normal([1], name='bias'))

def hypothesis():
    return tf.linalg.matmul(X, W) + b

def cost():
    return tf.reduce_mean(tf.square(hypothesis() - Y))

def train():
    return tf.keras.optimizers.SGD(learning_rate = 1e-5).minimize(cost, var_list=[W, b])

X.assign(x_data)
Y.assign(y_data)
for step in range(2001):
    train()
    if step % 200 == 0:
        print(step, cost().numpy(), hypothesis().numpy())

#1800 nan [[nan]
#  [nan]
#  [nan]
#  [nan]
#  [nan]
#  [nan]
#  [nan]
#  [nan]]
# 2000 nan [[nan]
#  [nan]
#  [nan]
#  [nan]
#  [nan]
#  [nan]
#  [nan]
#  [nan]]
# normalized 되지 않아서 이상한 값이 나옴
# minmax scale 필요

[[8.28659973e+02 8.33450012e+02 9.08100000e+05 8.28349976e+02]
 [8.23020020e+02 8.28070007e+02 1.82810000e+06 8.21655029e+02]
 [8.19929993e+02 8.24400024e+02 1.43810000e+06 8.18979980e+02]
 [8.16000000e+02 8.20958984e+02 1.00810000e+06 8.15489990e+02]
 [8.19359985e+02 8.23000000e+02 1.18810000e+06 8.18469971e+02]
 [8.19000000e+02 8.23000000e+02 1.19810000e+06 8.16000000e+02]
 [8.11700012e+02 8.15250000e+02 1.09810000e+06 8.09780029e+02]
 [8.09510010e+02 8.16659973e+02 1.39810000e+06 8.04539978e+02]] [[831.659973]
 [828.070007]
 [824.159973]
 [819.23999 ]
 [818.97998 ]
 [820.450012]
 [813.669983]
 [809.559998]]
0 3.0085074e+25 [[3.8690724e+12]
 [7.7888393e+12]
 [6.1271987e+12]
 [4.2951340e+12]
 [5.0620447e+12]
 [5.1046509e+12]
 [4.6785893e+12]
 [5.9567741e+12]]
200 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
400 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
600 nan [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
800 nan [[nan]
 [nan]
 [nan]
 [nan

In [6]:
import tensorflow as tf
import numpy as np

def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + ie-7)

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
xy = min_max(scaler(
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data, y_data)
X = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))
Y = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))

W = tf.Variable(tf.random.normal([4, 1], name='weight'))
b = tf.Variable(tf.random.normal([1], name='bias'))

def hypothesis():
    return tf.linalg.matmul(X, W) + b

def cost():
    return tf.reduce_mean(tf.square(hypothesis() - Y))

def train():
    return tf.keras.optimizers.SGD(learning_rate = 1e-5).minimize(cost, var_list=[W, b])

X.assign(x_data)
Y.assign(y_data)
for step in range(2001):
    train()
    if step % 200 == 0:
        print(step, cost().numpy(), hypothesis().numpy())


SyntaxError: invalid syntax (3775446706.py, line 18)