In [3]:
import tensorflow as tf

In [11]:
x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

X = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))
Y = tf.Variable(1., dtype=tf.float32, shape=tf.TensorShape(None))

W = tf.Variable(tf.random.normal([3, 3]))
b = tf.Variable(tf.random.normal([3]))

def hypothesis():
    return tf.nn.softmax(tf.linalg.matmul(X, W) + b)

def cost():
    return tf.reduce_mean(-tf.reduce_sum(Y * tf.math.log(hypothesis()), axis=1))

# 경사하강법
def train():
    return tf.keras.optimizers.SGD(learning_rate = 0.1).minimize(cost, var_list=[W, b])

In [12]:
X.assign(x_data)
Y.assign(y_data)
for step in range(201):
    train()
    print(step, cost().numpy(), W.numpy())

0 4.317541 [[ 1.8651212   0.795078   -0.54803723]
 [-0.16711627 -0.4147218  -0.12420749]
 [-0.5531424  -2.0446868  -0.16037787]]
1 3.3290749 [[ 1.8098637   0.8302708  -0.52797246]
 [-0.3449353  -0.24474464 -0.11636558]
 [-0.73151875 -1.8599602  -0.16672806]]
2 2.4538243 [[ 1.7916851   0.86072206 -0.5402452 ]
 [-0.33540824 -0.08646142 -0.2841758 ]
 [-0.72736675 -1.6827173  -0.3481229 ]]
3 1.9672229 [[ 1.7484592   0.88471544 -0.5210127 ]
 [-0.47377542  0.04956089 -0.28183097]
 [-0.87427217 -1.5233986  -0.3605362 ]]
4 1.8843793 [[ 1.7443773   0.8833761  -0.51559144]
 [-0.42103755  0.069075   -0.3540829 ]
 [-0.8364485  -1.468778   -0.45298043]]
5 1.8549716 [[ 1.7297016   0.87436587 -0.4919056 ]
 [-0.42373094  0.04325603 -0.32557055]
 [-0.85782284 -1.4581074  -0.44227678]]
6 1.833573 [[ 1.7183444   0.8667062  -0.47288874]
 [-0.40973192  0.02645604 -0.32276955]
 [-0.86056775 -1.4395912  -0.458048  ]]
7 1.8127906 [[ 1.7060125   0.85942715 -0.45327777]
 [-0.4013309   0.01185618 -0.3165707 ]
 [

In [13]:

# Correct prediction Test model
def prediction():
    return tf.math.argmax(hypothesis(), axis=1)

def isCorrect():
    return tf.equal(prediction(), tf.math.argmax(Y, 1))

def accuracy():
    return tf.reduce_mean(tf.cast(isCorrect(), tf.float32))
    
# predict
X.assign(x_test)
print("Prediction: ", prediction())

# Calculate the accuracy
Y.assign(y_test)
print("Accuracy: ", accuracy())

Prediction:  tf.Tensor([2 2 2], shape=(3,), dtype=int64)
Accuracy:  tf.Tensor(1.0, shape=(), dtype=float32)
