In [38]:
import numpy as np
import tensorflow as tf
import pprint as pp

In [42]:
# One Cell RNN input_dim (4) 4글자 -> output dim (2)로 설정
hidden_size = 2
x_data = np.array([[[1, 0, 0, 0]]], dtype=np.float32)
print(x_data.shape)
cell = tf.keras.layers.LSTMCell(units=hidden_size)
layer = tf.keras.layers.RNN(cell=cell, return_sequences=True)
whole_seq_output = layer(x_data)

print(whole_seq_output.numpy()) # hidden_size가 2개라서 2개의 결과값이 출력, (1, 1, 2)의 형태를 띔

(1, 1, 4)
[[[ 0.07003943 -0.12263874]]]


In [41]:
# One hot encoding
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

# One Cell RNN input_dim (4) -> output_dim (2), sequence: 5 (글자가 5개)
hidden_size = 2
x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
print(x_data.shape)
pp.pprint(x_data)
cell = tf.keras.layers.LSTMCell(units=hidden_size)
layer = tf.keras.layers.RNN(cell=cell, return_sequences=True)
whole_seq_output = layer(x_data)

print(whole_seq_output.numpy()) # hidden_size가 2개, sequence가 5개라서 (1, 5, 2)의 shape를 띔

(1, 5, 4)
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)
[[[-0.15294228 -0.09885784]
  [-0.19666603  0.01066832]
  [-0.21565965 -0.07234113]
  [-0.2283888  -0.11515839]
  [-0.21254335 -0.31121176]]]


In [44]:
# One Cell RNN input_dim(4) -> output_dim (2), sequence: 5, batch 3 (단어가 3개)
# Batching input
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)
pp.pprint(x_data)

cell = tf.keras.layers.LSTMCell(units=hidden_size) 
layer = tf.keras.layers.RNN(cell=cell, return_sequences=True)
whole_seq_output = layer(x_data)

print(whole_seq_output.numpy()) # hidden_size가 2개, sequence가 5개, batch_size가 3이라서 (3, 5, 2)의 형태

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]], dtype=float32)
[[[-0.12652412  0.08361943]
  [ 0.01670807 -0.02272644]
  [-0.00247627 -0.14991215]
  [-0.03121914 -0.234981  ]
  [-0.07974035 -0.09825514]]

 [[ 0.06448857 -0.08847655]
  [-0.02921549 -0.01475771]
  [-0.04876291 -0.14934081]
  [-0.05865896 -0.24049808]
  [-0.07087338 -0.3035825 ]]

 [[-0.01849764 -0.13252404]
  [-0.03950699 -0.22517744]
  [ 0.04246341 -0.2227427 ]
  [ 0.08268089 -0.24851772]
  [ 0.0514898  -0.34509566]]]
