In [7]:
hidden_size = 5 # output from the LSTM
input_dim = 5 # one-hot size, num_classes라고 표현하기도함
batch_size = 1 # 단어 수 one sentence
sequence_length = 6 # ihello = 6 글자수


In [4]:
import numpy as np
import tensorflow as tf

In [9]:
idx2char = ['h', 'i', 'e', 'l', 'o']
x_data = [[0, 1, 0, 2, 3, 3]] # hihell
x_one_hot = np.array([[[1, 0, 0, 0, 0],    # h 0
                       [0, 1, 0, 0, 0],    # i 1
                       [1, 0, 0, 0, 0],    # h 0
                       [0, 0, 1, 0, 0],    # e 2
                       [0, 0, 0, 1, 0],    # l 3
                       [0, 0, 0, 1, 0]]],  # l 3
                     dtype=np.float32)
y_data = [[1, 0, 2, 3, 3, 4]] # ihello
y_one_hot = tf.keras.utils.to_categorical(y_data, num_classes=hidden_size) # 원핫인코딩 함수
print(x_one_hot)
print(y_one_hot)

[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0.]]]
[[[0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]]


In [47]:
cell = tf.keras.layers.LSTMCell(units=hidden_size, input_shape=(sequence_length, input_dim))
layer = tf.keras.layers.RNN(cell=cell, return_sequences=True) # initial_state는 따로 지정되지 않으면 zero state 제공
# whole_seq_output = layer(x_one_hot)
# print(whole_seq_output.numpy(), whole_seq_output.shape) # batch 1, sequence_length 6, hidden_size 5

In [48]:
model = tf.keras.Sequential()
model.add(layer)
model.add(tf.keras.layers.Dense(units=hidden_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(learning_rate=0.1), metrics=['accuracy'])
model.build(input_shape=(1, sequence_length, input_dim))
model.summary()

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 rnn_9 (RNN)                 (1, 6, 5)                 220       
                                                                 
 dense_1 (Dense)             (1, 6, 5)                 30        
                                                                 
Total params: 250 (1000.00 Byte)
Trainable params: 250 (1000.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [49]:
model.fit(x_one_hot, y_one_hot, epochs=50)

Epoch 1/50
1/1 [==============================] - 1s 793ms/step - loss: 1.5806 - accuracy: 0.3333
Epoch 2/50
1/1 [==============================] - 0s 5ms/step - loss: 1.4756 - accuracy: 0.3333
Epoch 3/50
1/1 [==============================] - 0s 4ms/step - loss: 1.3865 - accuracy: 0.3333
Epoch 4/50
1/1 [==============================] - 0s 4ms/step - loss: 1.2939 - accuracy: 0.5000
Epoch 5/50
1/1 [==============================] - 0s 4ms/step - loss: 1.1732 - accuracy: 0.5000
Epoch 6/50
1/1 [==============================] - 0s 5ms/step - loss: 1.0254 - accuracy: 0.6667
Epoch 7/50
1/1 [==============================] - 0s 4ms/step - loss: 0.8830 - accuracy: 1.0000
Epoch 8/50
1/1 [==============================] - 0s 4ms/step - loss: 0.7397 - accuracy: 1.0000
Epoch 9/50
1/1 [==============================] - 0s 4ms/step - loss: 0.6093 - accuracy: 1.0000
Epoch 10/50
1/1 [==============================] - 0s 4ms/step - loss: 0.4994 - accuracy: 1.0000
Epoch 11/50
1/1 [====================

In [54]:
predictions = model.predict(x_one_hot) # hihell의 다음글자들은?
for i, pred in enumerate(predictions):
    print(pred)
    # 결과 출력
    result_str = [idx2char[c] for c in np.argmax(pred, axis=1)]
    print("Predict: ", ''.join(result_str)) # Predict:  ihello

1/1 [==============================] - 0s 11ms/step
[[8.6090142e-07 9.9857950e-01 1.1406707e-03 2.7893210e-04 7.7554681e-08]
 [9.9752492e-01 2.2408129e-07 1.7981237e-03 1.8021115e-04 4.9661566e-04]
 [5.8125972e-04 1.3566954e-03 9.9805427e-01 7.2645753e-06 5.7981492e-07]
 [5.2530366e-05 9.0026224e-05 3.9712620e-07 9.9984753e-01 9.5648666e-06]
 [9.8354772e-05 2.2640752e-04 3.9643096e-06 9.9869448e-01 9.7683736e-04]
 [5.7450513e-04 4.2347070e-05 1.2674677e-05 1.1938886e-03 9.9817657e-01]]
Predict:  ihello
