In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

2024-03-02 07:01:05.503283: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
train_X =  [[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_X)) # 단어 벡터의 차원 5, 문장의 길이 4
# 4번의 시점(timesteps)가 존재하고, 각 시점마다 5개의 단어 벡터가 입력으로 사용됨.

(4, 5)


In [7]:
# 단 RNN은 2D텐서가 아니고 3D 텐서를 입력으로 받으므로 배치 크기 1을 추가
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape) # batch_size는 1이고 RNN이 학번에 학습하는 양

(1, 4, 5)


In [9]:
#SimpleRNN의 이해

rnn = SimpleRNN(3) # 은닉 상태의 크기 3
# rnn = SimpleRNN(3, return_sequences = False, return_state=False)와 동일
hidden_state = rnn(train_X)

# 마지막 시점의 은닉 상태 (return_sequences = FALSE 이므로)
print('hidden_state, {}, shape: {}'.format(hidden_state, hidden_state.shape))
# 1,3 크기의 텐서가 출력됨

hidden_state, [[-0.6358631  0.9584665 -0.8605274]], shape: (1, 3)


In [11]:
#return_sequences=True : 모든 시점(timestep4이므로 4개의 시점)에 대한 은닉 상태의 값을 출력하므로 (1, 4, 3)의 크기를 가지는 출력값이 나올 것임
rnn = SimpleRNN(3, return_sequences=True)
hidden_states = rnn(train_X)

print('hidden states = {}, shape: {}'.format(hidden_states, hidden_states.shape))

hidden states = [[[-0.99610096  0.99202013  0.99230736]
  [-0.7448218   0.99385846  0.90548515]
  [ 0.80619574  0.45831093  0.92525667]
  [-0.9695835   0.27544782  0.9586299 ]]], shape: (1, 4, 3)


In [16]:
#return_state가 True일 경우 return_sequences와 상관없이 마지막 시점의 은닉상태를 출력
#둘다 True이면 두개의 출력을 리턴
rnn = SimpleRNN(3, return_state=True, return_sequences=True)
hidden_states, last_state = rnn(train_X)

print('hidden states = {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state = {}, shape: {}'.format(last_state, last_state.shape))

hidden states = [[[ 0.659799   -0.99954146 -0.7778292 ]
  [ 0.37334204 -0.98794866 -0.9699287 ]
  [ 0.9119409  -0.30625758 -0.9881479 ]
  [ 0.77707785 -0.9647821   0.28118294]]], shape: (1, 4, 3)
last hidden state = [[ 0.77707785 -0.9647821   0.28118294]], shape: (1, 3)


In [21]:
# return_sequences False인데 return_state True인 경우는, 두개의 출력 모두 마지막 은닉 상태
rnn = SimpleRNN(3, return_state=True, return_sequences=False)
hidden_states, last_state = rnn(train_X)

print('hidden states = {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state = {}, shape: {}'.format(last_state, last_state.shape))

hidden states = [[ 0.9975329  -0.92157096  0.0579496 ]], shape: (1, 3)
last hidden state = [[ 0.9975329  -0.92157096  0.0579496 ]], shape: (1, 3)
