In [3]:
# keras의 texts_to_matrix 이해하기
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

texts=['먹고 싶은 사과', '먹고 싶은 바나나', '길고 노란 바나나 바나나', '저는 과일이 좋아요']

#정수 인덱스 부여
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
print(tokenizer.word_index)


{'바나나': 1, '먹고': 2, '싶은': 3, '사과': 4, '길고': 5, '노란': 6, '저는': 7, '과일이': 8, '좋아요': 9}


In [5]:
print(tokenizer.texts_to_matrix(texts, mode = 'count')) # texts_to_matrix: 텍스트로 행렬 만듬
#count: 단어 행렬 생성(Document Term Matrix, DTM), 정수 인덱스 기준으로 각 인덱스의 문자 빈도를 출력

[[0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]]


In [7]:
print(tokenizer.texts_to_matrix(texts, mode = 'binary'))
#binary: DTM과 유사하지만 존재여부만 표현

[[0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]]


In [9]:
print(tokenizer.texts_to_matrix(texts, mode = 'tfidf'))
#tfidf: tf-idf 행렬을 만듬

[[0.         0.         0.84729786 0.84729786 1.09861229 0.
  0.         0.         0.         0.        ]
 [0.         0.84729786 0.84729786 0.84729786 0.         0.
  0.         0.         0.         0.        ]
 [0.         1.43459998 0.         0.         0.         1.09861229
  1.09861229 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         1.09861229 1.09861229 1.09861229]]


In [13]:
print(tokenizer.texts_to_matrix(texts, mode = 'freq'))
#freq: 문서 크기 대비 빈도 비율

[[0.         0.         0.33333333 0.33333333 0.33333333 0.
  0.         0.         0.         0.        ]
 [0.         0.33333333 0.33333333 0.33333333 0.         0.
  0.         0.         0.         0.        ]
 [0.         0.5        0.         0.         0.         0.25
  0.25       0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.33333333 0.33333333 0.33333333]]
