In [2]:
import numpy as np

In [3]:
# 벡터나 행렬의 덧셈과 뺄셈은 같은 위치의 원소끼리 연산하면 된다.
# 이러한 연산을 요소별 연산(element-wise)라고 한다.
A = np.array([8, 4, 5])
B = np.array([1, 2, 3])
print('두 벡터의 합 :',A+B)
print('두 벡터의 차 :',A-B)

두 벡터의 합 : [9 6 8]
두 벡터의 차 : [7 2 2]


In [4]:
# 행렬도 마찬가지 element-wise 진행
A = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
B = np.array([[5, 6, 7, 8],[1, 2, 3, 4]])
print('두 행렬의 합 :')
print(A + B)
print('두 행렬의 차 :')
print(A - B)

두 행렬의 합 :
[[15 26 37 48]
 [51 62 73 84]]
두 행렬의 차 :
[[ 5 14 23 32]
 [49 58 67 76]]


In [5]:
# 벡터의 점곱(dot-product) 또는 내적(inner-product)
# 벡터의 내적은 연산을 점(dot)으로 표현한다.
# 내적이 성립하려면 차원이 같아야한다. 두 벡터 중 앞의 벡터가 행벡터(가로 방향 벡터), 뒤의 벡터가 열벡터(세로 방향 벡터)여야 한다.
# 벡터의 내적의 결과는 스칼라가 된다.
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print('두 벡터의 내적 :', np.dot(A, B))

두 벡터의 내적 : 32


In [8]:
# 행렬의 곱셉은 왼쪽 행렬의 행벡터(가로 방향 벡터)와 오른쪽 행렬의 열벡터(세로 방향 벡터)의 내적이 결과 행렬의 원소가 된다.
A = np.array([[1, 3],[2, 4]])
B = np.array([[5, 7],[6, 8]])
print('두 행렬의 행렬곱 :')
print(np.matmul(A, B)) # [[1*5 + 3*6 1*7 + 3*8], [2*5 + 4*6 2*7 + 4*8]]
# 두 행렬의 곱 A X B가 성립되기 위해서는 행렬 A의 열의 개수와 행렬 B의 행의 개수는 같아야 한다.
# 두 행렬의 곱 A X B의 결과로 나온 행렬 AB의 크기는 A의 행의 개수와 B의 열의 개수를 가진다.

두 행렬의 행렬곱 :
[[23 31]
 [34 46]]


In [ ]:
# 독립 변수 x가 n개인 다중 선형 회귀 수식
# y = w1x1 + w2x2 + ... + wnxn + b는 입력 벡터[x1...xn]과 가중치 벡터[w1...wn]의 내적으로 표현 가능
# y = [x1 x2 x3... xn] * [w1 w2 w3... wn] + b = x1w1 + x2w2 ... + xnwn +b 가 된다. (입력, 가중치의 순서가 바뀌어도 상관은 없다)
# 샘플의 개수가 많을 경우에는 행렬의 곱셈으로 표현 가능